    
    zn "USER"
    #; do $SYSTEM.OBJ.Load("/home/irisowner/dev/zpm-0.10.7.xml","ck")
    set r=##class(%Net.HttpRequest).%New(),r.Server="pm.community.intersystems.com",r.SSLConfiguration="ISC.FeatureTracker.SSL.Config" d r.Get("/packages/zpm/latest/installer"),$system.OBJ.LoadStream(r.HttpResponse.Data,"c")

    zpm "enable -map -globally"
    zpm "enable -community"
    zpm "install swagger-ui" 
 
    zn "%SYS"

    set app = "/csp/training"
    set appProperties("DeepSeeEnabled")=1
    set sc = ##class(Security.Applications).Modify(app,.appProperties)
    
    zn "TRAINING"

    // Load the Python demo module (compiles classes, copies Python, installs pip deps)
    zpm "load -nodev /home/irisowner/dev -v"

    halt