services:

  iris-dev:
    build:
      args:
        IMAGE: containers.intersystems.com/intersystems/irishealth-community:latest-em
      context: iris-dev
    container_name: ${IRIS_INSTANCE_NAME}-dev
    hostname: ${IRIS_INSTANCE_NAME}-dev
    ports:
      - ${IRIS_PORT_DEV}:1972
      - ${IRIS_WEBSERVER_PORT}:52773 # *Only* used for Community Edition for VS Code ObjectScript extension to connect to /api/atelier and for IRIS Administration Portal
    volumes:
      - dev_${ISC_DATA_DIRECTORY}_${IRIS_INSTANCE_NAME}:/${ISC_DATA_DIRECTORY}
      - ./iris/python/iris_python_demo:/usr/irissys/mgr/python/iris_python_demo
      - ./iris/src:/code
      - ./data:/data
      - ./merge-dev.cpf:/merge.cpf
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris
      - ISC_DATA_DIRECTORY=/${ISC_DATA_DIRECTORY}
      - ISC_CPF_MERGE_FILE=/merge.cpf
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION}
      - AZURE_OPENAI_EMBEDDING_DEPLOYMENT=${AZURE_OPENAI_EMBEDDING_DEPLOYMENT}
  iris:
    build:
      args:
        IMAGE: containers.intersystems.com/intersystems/irishealth:latest-em
      context: iris
    container_name: ${IRIS_INSTANCE_NAME}
    hostname: ${IRIS_INSTANCE_NAME}
    ports:
      - ${IRIS_PORT}:1972
    volumes:
      - ${ISC_DATA_DIRECTORY}_${IRIS_INSTANCE_NAME}:/${ISC_DATA_DIRECTORY}
      - journal_${IRIS_INSTANCE_NAME}:/journal
      - journal2_${IRIS_INSTANCE_NAME}:/journal2
      - WIJ_${IRIS_INSTANCE_NAME}:/WIJ
      - ./iris/key/iris.key:/tmp/iris.key:ro
      - ./iris/python/iris_python_demo:/usr/irissys/mgr/python/iris_python_demo
      - ./iris/src:/code
      - ./data:/data
      - ./merge.cpf:/merge.cpf
    command: --key /tmp/iris.key
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris
      - ISC_DATA_DIRECTORY=/${ISC_DATA_DIRECTORY}
      - ISC_CPF_MERGE_FILE=/merge.cpf
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION}
      - AZURE_OPENAI_EMBEDDING_DEPLOYMENT=${AZURE_OPENAI_EMBEDDING_DEPLOYMENT}
 
  webgateway: # Used for VS Code ObjectScript extension to connect to /api/atelier and for IRIS Administration Portal and Web Services
    image: containers.intersystems.com/intersystems/webgateway:latest-em
    depends_on:
      - iris
    ports:
      - ${WEBGATEWAY_PORT_HTTP}:80
      - ${WEBGATEWAY_PORT_HTTPS}:443
    restart: unless-stopped
    environment:
    - ISC_CSP_CONF_FILE=/webgateway/CSP.conf
    - ISC_CSP_INI_FILE=/webgateway/CSP.ini
    volumes:
    - type: bind
      source: ./webgateway
      target: /webgateway
    networks:
      - default
 
volumes:
  dev_databases_iris-health-training:
  databases_iris-health-training:
  journal_iris-health-training:
  journal2_iris-health-training:
  WIJ_iris-health-training: