services:

  iris-dev:
    build:
      args:
        IMAGE: containers.intersystems.com/intersystems/irishealth-community:latest-em
      context: iris
    container_name: ${IRIS_INSTANCE_NAME}-dev-local
    hostname: ${IRIS_INSTANCE_NAME}-dev
    ports:
      - ${IRIS_PORT_DEV_LOCAL}:1972
      - 39000-39200:9000-9200
    volumes:
      - dev_${ISC_DATA_DIRECTORY}:/${ISC_DATA_DIRECTORY}
      - dev_journal:/journal
      - dev_journal2:/journal2
      - dev_WIJ:/WIJ
      - ./iris/src:/code
      - ./data:/data
      - ./merge-dev-community.cpf:/merge.cpf
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris
      - ISC_DATA_DIRECTORY=/${ISC_DATA_DIRECTORY}
      - ISC_CPF_MERGE_FILE=/merge.cpf
  iris-prod:
    build:
      args:
        IMAGE: containers.intersystems.com/intersystems/irishealth-community:latest-em
      context: iris
    container_name: ${IRIS_INSTANCE_NAME}-prod-local
    hostname: ${IRIS_INSTANCE_NAME}-prod
    ports:
      - ${IRIS_PORT_PROD_LOCAL}:1972
      - 39500-39700:9500-9700
    volumes:
      - prod_${ISC_DATA_DIRECTORY}:/${ISC_DATA_DIRECTORY}
      - prod_journal:/journal
      - prod_journal2:/journal2
      - prod_WIJ:/WIJ
      - ./iris/src:/code
      - ./data:/data
      - ./merge-prod-community.cpf:/merge.cpf
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris
      - ISC_DATA_DIRECTORY=/${ISC_DATA_DIRECTORY}
      - ISC_CPF_MERGE_FILE=/merge.cpf
 
  webgateway: # Used for VS Code ObjectScript extension to connect to /api/atelier and for IRIS Administration Portal and Web Services
    image: containers.intersystems.com/intersystems/webgateway:latest-em
    container_name: ${IRIS_INSTANCE_NAME}-webgateway-local
    depends_on:
      - iris-dev
      - iris-prod
    ports:
      - ${WEBGATEWAY_PORT_HTTP_LOCAL}:80
      - ${WEBGATEWAY_PORT_HTTPS_LOCAL}:443
    restart: unless-stopped
    environment:
    - ISC_CSP_CONF_FILE=/webgateway/CSP.conf
    - ISC_CSP_INI_FILE=/webgateway/CSP.ini
    volumes:
    - type: bind
      source: ./webgateway
      target: /webgateway
    networks:
      - default
 
volumes:
  dev_databases:
    external: true
    name: ${IRIS_INSTANCE_NAME}-local_dev_databases  
  dev_journal:
    external: true
    name: ${IRIS_INSTANCE_NAME}-local_dev_journal
  dev_journal2:
    external: true
    name: ${IRIS_INSTANCE_NAME}-local_dev_journal2
  dev_WIJ:
    external: true
    name: ${IRIS_INSTANCE_NAME}-local_dev_WIJ
  prod_databases:
    external: true
    name: ${IRIS_INSTANCE_NAME}-local_prod_databases
  prod_journal:
    external: true
    name: ${IRIS_INSTANCE_NAME}-local_prod_journal
  prod_journal2:
    external: true
    name: ${IRIS_INSTANCE_NAME}-local_prod_journal2
  prod_WIJ:
    external: true
    name: ${IRIS_INSTANCE_NAME}-local_prod_WIJ