
### Create REST API

POST http://localhost/iris-health-training-dev/api/mgmnt/v2/TRAINING/fhirfoch
Accept: application/json
Content-Type: application/json
Authorization: Basic X3N5c3RlbTpJUklTNEdvb2Qv

< ./swagger/fhir.json

### DEV LOCAL - ORU
POST http://localhost/iris-health-training-dev/csp/healthshare/dglab/EnsLib.HL7.Service.HTTPService.cls?CfgItem=LAB RESULT from DGLAB - HTTP HTTP/1.1
Content-Type: text/plain; charset=utf-8
Authorization: Basic X3N5c3RlbTpJUklTNEdvb2Qv

< ./docs/20260610_144322985_DEF_6100130_000043.HL7


### DEV LOCAL - ADT
POST http://localhost/iris-health-training-dev/csp/healthshare/dglab/EnsLib.HL7.Service.HTTPService.cls?CfgItem=Patient Information from IHE PAM - HTTP HTTP/1.1
Content-Type: text/plain; charset=utf-8
Authorization: Basic X3N5c3RlbTpJUklTNEdvb2Qv

< ./docs/1-ADT.hl7


### IRIS instance details and timestamp
GET http://localhost/iris-health-training-dev/foch/version HTTP/1.1
Accept: application/json
Authorization: Basic X3N5c3RlbTpJUklTNEdvb2Qv

@specFirstFochBaseUrl = http://localhost/iris-health-training-dev/specfirst/foch
@specFirstFochPatientId = 2
@specFirstFochTarget = fhir
@specFirstFochAuthorization = Basic X3N5c3RlbTpJUklTNEdvb2Qv

### SPEC FIRST FOCH - IRIS instance details
GET {{specFirstFochBaseUrl}}/version HTTP/1.1
Accept: application/json
Authorization: {{specFirstFochAuthorization}}

### SPEC FIRST FOCH - IRIS instance details from Embedded Python
GET {{specFirstFochBaseUrl}}/versionpy HTTP/1.1
Accept: application/json
Authorization: {{specFirstFochAuthorization}}

### SPEC FIRST FOCH - project the source patient as FHIR without persisting it
GET {{specFirstFochBaseUrl}}/Patient/{{specFirstFochPatientId}} HTTP/1.1
Accept: application/fhir+json
Authorization: {{specFirstFochAuthorization}}

### SPEC FIRST FOCH - synchronize with POST or PUT according to target existence
POST {{specFirstFochBaseUrl}}/Patient?target={{specFirstFochTarget}} HTTP/1.1
Accept: application/fhir+json
Content-Type: application/fhir+json
Authorization: {{specFirstFochAuthorization}}

{
  "resourceType": "Patient",
  "id": "HHFOCH001",
  "identifier": [
    {
      "system": "urn:oid:1.2.250.1.999.1",
      "value": "HHFOCH001"
    },
    {
      "system": "urn:oid:1.2.250.1.213.1.4.8",
      "value": "HHSYSTEM001"
    },
    {
      "system": "urn:oid:1.2.250.1.213.1.4.10",
      "value": "19DSF FDSF FSDF9"
    }
  ],
  "active": true,
  "name": [
    {
      "use": "official",
      "family": "MOREAU",
      "given": [
        "Dimitri"
      ]
    },
    {
      "use": "maiden",
      "family": "DUPONT"
    }
  ],
  "telecom": [
    {
      "system": "email",
      "value": "T6121@example.com"
    },
    {
      "system": "phone",
      "value": "N2980",
      "use": "mobile"
    },
    {
      "system": "phone",
      "value": "325-518-1140",
      "use": "home"
    },
    {
      "system": "phone",
      "value": "M7029",
      "use": "temp"
    }
  ],
  "gender": "other",
  "birthDate": "1957-11-30",
  "deceasedDateTime": "1939-08-04",
  "address": [
    {
      "use": "home",
      "line": [
        "25 rue des Vignes"
      ],
      "city": "Suresnes",
      "postalCode": "92500",
      "country": "FR"
    }
  ],
  "extension": [
    {
      "url": "http://hl7.org/fhir/StructureDefinition/patient-birthPlace",
      "valueAddress": {
        "line": [
          "3391 Madison Court",
          "P9968",
          "R3740",
          "C6301"
        ],
        "city": "Boston",
        "postalCode": "88019",
        "country": "V4487"
      }
    }
  ]
}

### SPEC FIRST FOCH - update the home address and force an idempotent FHIR PUT
PUT {{specFirstFochBaseUrl}}/Patient/{{specFirstFochPatientId}}?target={{specFirstFochTarget}} HTTP/1.1
Accept: application/fhir+json
Content-Type: application/fhir+json
Authorization: {{specFirstFochAuthorization}}

{
	"resourceType": "Patient",
  "id": "{{specFirstFochPatientId}}",
  "identifier": [],
  "active": true,
  "name": [],
  "telecom": [],
  "gender": "unknown",
	"address": [
		{
			"use": "home",
			"line": [
				"25 rue des Vignes"
			],
			"city": "Suresnes",
			"postalCode": "92500",
			"country": "FR"
		}
	]
}

### SPEC FIRST FOCH - delete the target FHIR Patient and preserve data.patient
DELETE {{specFirstFochBaseUrl}}/Patient/{{specFirstFochPatientId}} HTTP/1.1
Accept: application/fhir+json
Authorization: {{specFirstFochAuthorization}}

### IRIS instance details and timestamp
GET http://localhost/iris-health-training-dev/fhir/version HTTP/1.1
Accept: application/json
Authorization: Basic X3N5c3RlbTpJUklTNEdvb2Qv

### IRIS instance details and timestamp - Embedded Python
GET http://localhost/iris-health-training-dev/fhir/versionpy HTTP/1.1
Accept: application/json
Authorization: Basic X3N5c3RlbTpJUklTNEdvb2Qv

### FHIR facade - project data.patient ID 1 without persisting it
GET http://localhost/iris-health-training-dev/fhir/Patient/1 HTTP/1.1
Accept: application/fhir+json
Authorization: Basic X3N5c3RlbTpJUklTNEdvb2Qv

### FHIR synchronization - POST when IPP is absent, PUT when it already exists
POST http://localhost/iris-health-training-dev/fhir/Patient/1 HTTP/1.1
Accept: application/fhir+json
Content-Type: application/fhir+json
Authorization: Basic X3N5c3RlbTpJUklTNEdvb2Qv

{
	"resourceType": "Patient",
	"id": "J7720",
	"identifier": [
		{
      "system": "urn:oid:1.2.250.1.999.1",
			"value": "J7720"
		}
	]
}

### FHIR synchronization - force an idempotent PUT
PUT http://localhost/iris-health-training-dev/fhir/Patient/1 HTTP/1.1
Accept: application/fhir+json
Content-Type: application/fhir+json
Authorization: Basic X3N5c3RlbTpJUklTNEdvb2Qv

{
	"resourceType": "Patient",
	"id": "J7720",
	"identifier": [
		{
      "system": "urn:oid:1.2.250.1.999.1",
			"value": "J7720"
		}
	],
	"address": [
		{
			"use": "home",
			"line": [
				"25 avenue de la Republique"
			],
			"city": "Paris",
			"postalCode": "75011",
			"country": "FR"
		}
	]
}

### DEV COMMUNITY - ORU
POST http://localhost:881/iris-health-training-dev/csp/healthshare/dglab/EnsLib.HL7.Service.HTTPService.cls?CfgItem=LAB RESULT from DGLAB - HTTP HTTP/1.1
Content-Type: text/plain; charset=utf-8
Authorization: Basic X3N5c3RlbTpTWVM=

< ./docs/20260610_144322985_DEF_6100130_000043.HL7


### DEV COMMUNITY - ADT
POST http://localhost:881/iris-health-training-dev/csp/healthshare/dglab/EnsLib.HL7.Service.HTTPService.cls?CfgItem=Patient Information from IHE PAM - HTTP HTTP/1.1
Content-Type: text/plain; charset=utf-8
Authorization: Basic X3N5c3RlbTpTWVM=

< ./docs/1-ADT.hl7

### DEV AWS - ORU
POST http://ec2-63-177-72-122.eu-central-1.compute.amazonaws.com/iris-health-training-dev/csp/healthshare/dglab/EnsLib.HL7.Service.HTTPService.cls?CfgItem=aaa HTTP/1.1
Content-Type: text/plain; charset=utf-8
Authorization: Basic X3N5c3RlbTpJUklTNEdvb2Qv

< ./docs/20260610_144322985_DEF_6100130_000043.HL7


### DEV AWS - ADT
POST http://ec2-63-177-72-122.eu-central-1.compute.amazonaws.com/iris-health-training-dev/csp/healthshare/dglab/EnsLib.HL7.Service.HTTPService.cls?CfgItem=aaa HTTP/1.1
Content-Type: text/plain; charset=utf-8
Authorization: Basic X3N5c3RlbTpJUklTNEdvb2Qv

< ./docs/1-ADT.hl7
